[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-framework CoreFoundation -framework Security"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-framework CoreFoundation -framework Security"]